find_path(GLM_INCLUDE_DIR NAMES glm PATHS ${CONAN_INCLUDE_DIRS_GLM} NO_CMAKE_FIND_ROOT_PATH)

message("** GLM ALREADY FOUND BY CONAN!")
set(GLM_FOUND TRUE)
message("** FOUND GLM INCLUDE:  ${GLM_INCLUDE_DIR}")

set(GLM_INCLUDE_DIRS ${GLM_INCLUDE_DIR};${GLM_INCLUDE_DIR}/glm)

mark_as_advanced(GLM_ROOT GLM_INCLUDE_DIR)

set(GLM_MAJOR_VERSION "0")
set(GLM_MINOR_VERSION "9")
set(GLM_PATCH_VERSION "8")
set(GLM_TWEAK_VERSION "5")
