if (GLM_FOUND OR TARGET GLM)
	RETURN()
endif()

find_path(GLM_INCLUDE_DIR NAMES glm PATHS ${CMAKE_CURRENT_LIST_DIR} NO_CMAKE_FIND_ROOT_PATH)
set(GLM_FOUND TRUE)
set(GLM_INCLUDE_DIRS ${GLM_INCLUDE_DIR})

mark_as_advanced(GLM_ROOT GLM_INCLUDE_DIR GLM_INCLUDE_DIRS GLM_FOUND)

add_library(GLM INTERFACE IMPORTED)

set_target_properties(GLM PROPERTIES
  INTERFACE_INCLUDE_DIRECTORIES ${GLM_INCLUDE_DIRS}
)

set(GLM_MAJOR_VERSION "0")
set(GLM_MINOR_VERSION "9")
set(GLM_PATCH_VERSION "9")
set(GLM_TWEAK_VERSION "3")
